print("おはようございます")
print("コーヒーがないとムリ")
print("今日はいいてんきですね")
print("がっこうにいきたくない")
print("チルしてたいだけ")
print("これはマジでヤバい")
print("study hard, sleep later")
print("さいきんちょっとつかれてる")
print("アイラブジャパン")
print("このゲームはガチでおもしろい")
print("Let’s take a break")
print("やっぱりカフェがいちばん")
print("もっとねたい…")
print("ナイスチャレンジだったね")
print("Can’t focus today")
print("あしたはきっとだいじょうぶ")
print("テンションがゼロです")
print("えいごのべんきょうしなきゃ")
print("もうすぐランチタイム")
print("Keep going, you got this")